# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes to the default branch
  push:
    branches: ["main"]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Control concurrency
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  # This is optional/auto-set
    runs-on: ubuntu-latest
    
    steps:
      # 1) Check out your repository code
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Set up Node so you can run npm commands
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3) Install dependencies
      - name: Install dependencies
        run: npm install

      # 4) Build your project (run your build script from package.json)
      - name: Build
        run: npm run build

      # 5) Set up GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 6) Upload the generated static files as an artifact for deployment
      #    Replace './build' with your actual output folder (e.g., 'dist' for Vite)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'

      # 7) Deploy uploaded artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
